apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project-deploy1
  template:
    metadata:
      name: project-pod1
      labels:
        name: mydeploy1
    spec:
      containers:
      - name: project-container
        image: rajavardhanrg30/ci-cd-pipeline:latest   # replace with your Docker-image pushed on Dockerhub
        ports:
        - containerPort: 8080

